spring.application.name=RESTAPI-ToDo-Management
logging.level.org.springframework.security=DEBUG
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.todo_mgmt=INFO

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/todo_management
spring.datasource.username=root
spring.datasource.password=password

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT
#SHA256 encoded value for priyanka
app.jwt-secret=a1fd973ae59aace78a9c6bc74a6f3d39d903dc2b7e2b7bf215f3670681f2d1e6
app.jwt-expiration-milliseconds=604800000
