spring.application.name=RESTAPI-EmployeeManagement
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.employee_mgmt=DEBUG

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management
spring.datasource.username=root
spring.datasource.password=password

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
