spring.application.name=RESTAPI-BankingSystem
logging.level.root=info

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=password

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*

# Actuator /info endpoint
management.info.env.enabled=true
info.app.name="Spring Boot REST API - Banking Application"
info.app.description="Spring Boot REST API - Banking Application"
info.app.version="v1.0.0"

# Actuator /health endpoint
management.endpoint.health.show-details=always





